### ISSUE TITLE
UI bug

### ISSUE THREAD

**Issue by Ardian-Hoti** [Aslam97/shadcn-minimal-tiptap#1]
In the button for Open in New Tab at the link in the dark mode the button doesn't notice (its the same color as backgorund) at least at me with  [Dark reader]([darkreader.org/](https://darkreader.org/)) chrome extension

**Comment by Aslam97** [comment]
@Ardian-Hoti Thank you for letting me know. However, I believe you can directly adjust the CSS in the switch component provided by shadcn.
