### ISSUE TITLE
Image not rendering after saving

### ISSUE THREAD

**Issue by lanoow** [Aslam97/shadcn-minimal-tiptap#19]
# Issue
So i've been creating a blog-type website and I want to be able to use images of course, however after I add an image link and save the content, the image is no longer rendered.

# Preview
[issue_preview_video.webm](https://github.com/user-attachments/assets/cc27c3a7-62d9-44c9-8ff1-70648b82a5f8)

# Other
I tried modifying the `ImageViewBlock` component aswell, using next/image and default `img` tag however there's no change.

**Comment by Aslam97** [comment]
@lanoow When you add an image, it does not trigger the onChange event. To solve this, you need to create a new paragraph so that the img attributes are included in the onChange event. However, this approach isn't ideal. In this case, I would suggest adding something like `editor.commands.createParagraphNear()` after adding the image. It would look something like this:

```ts
// image-edit-block.tsx
const handleLink = () => {
  editor.chain().focus().setImage({ src: link }).run()
  editor.commands.createParagraphNear()
  close()
}

const handleFile = (e: React.ChangeEvent<HTMLInputElement>) => {
  const files = e.target.files
  if (!files) return
  const reader = new FileReader()
  reader.onload = e => {
    const src = e.target?.result as string
    editor.chain().focus().setImage({ src }).run()
    editor.commands.createParagraphNear()
  }
  reader.readAsDataURL(files[0])
  close()
}
```

**Comment by Aslam97** [comment]
@lanoow I still don't have the time yet to finish all the remaining features, including images. But the above answer should be enough to fix your issue.

**Comment by Aslam97** [comment]
@lanoow Could it be related to the `throttleDelay` prop? Setting it to 0 might give you immediate updates.

**Comment by lanoow** [comment]
> @lanoow When you add an image, it will not trigger the onChange if you don't have any paragraph set. However, in your video, you do have a paragraph. To ensure that the onChange event is always triggered when an image is added, you can do something like this:
> 
> ```ts
> // image-edit-block.tsx
> const handleLink = () => {
>   editor.chain().focus().setImage({ src: link }).run()
>   editor.commands.createParagraphNear()
>   close()
> }
> 
> const handleFile = (e: React.ChangeEvent<HTMLInputElement>) => {
>   const files = e.target.files
>   if (!files) return
>   const reader = new FileReader()
>   reader.onload = e => {
>     const src = e.target?.result as string
>     editor.chain().focus().setImage({ src }).run()
>     editor.commands.createParagraphNear()
>   }
>   reader.readAsDataURL(files[0])
>   close()
> }
> ```

So I did try doing that, however it's still not rendering.

**Comment by lanoow** [comment]
> @lanoow Could it be related to the `throttleDelay` prop? Setting it to 0 might give you immediate updates.

It's currently set at `1000`, tried setting it at `0` but no chanage. It's still not rendering it. When inspecting the image tag is there and the src is there as well but it's not rendering it.

**Comment by Aslam97** [comment]
@lanoow Could you create a minimal reproduction using StackBlitz or a similar online code editor and share the link here? This would help me understand and troubleshoot the problem more effectively.

**Comment by lanoow** [comment]
> @lanoow Could you create a minimal reproduction using StackBlitz or a similar online code editor and share the link here? This would help me understand and troubleshoot the problem more effectively.

Yeah sure, give me a few minutes!

**Comment by lanoow** [comment]
@Aslam97 here's a reproduction of the repo. [link](https://stackblitz.com/~/github.com/lanoow-dev/firstbulgarianchoir)

**Comment by Aslam97** [comment]
@lanoow You almost got the whole code there 😅. Anyway, I couldn't try it because of dependency errors, but I have tried to reproduce it myself and it's all working fine. The only issue I found was that whenever the submit button was clicked, my own form got submitted too. This was fixed here: #21 and I added an example here that you can take a look at: #22 


https://github.com/user-attachments/assets/582d0045-b922-4786-828f-d3634c9838e8

**Comment by lanoow** [comment]
You should be able to run it if you do `npm install --force`, i'm using `bun` and idk what's the problem with `npm`.
The problem I'm having isn't related to the form but to the image not rendering for unknown reasons. I'm gonna try something but I'm not sure it'll work. I'll include a preview after I try it

**Comment by lanoow** [comment]
@Aslam97 so what's interesting is, this is the url that's put in `<img>`
![image](https://github.com/user-attachments/assets/75a4416a-1fdd-4052-a295-b353f93f85aa)

**Comment by Aslam97** [comment]
@lanoow and whats the url that being save to the database?

**Comment by lanoow** [comment]
@Aslam97 Here's what's in the DB column:

```html
"<img src=\"\\&quot;https://images.unsplash.com/photo-1727707185480-a50e6090b58c?q=80&amp;w=2071&amp;auto=format&amp;fit=crop&amp;ixlib=rb-4.0.3&amp;ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA\\&quot;\"><p class=\"text-node\">nrjgnjrngjrng</p><img src=\"https://images.unsplash.com/photo-1725203574073-79922f64110a\"><p class=\"text-node\"></p>"
```

**Comment by lanoow** [comment]
And that's the error I get if I try to use next/image
```
Error: Failed to parse src "\"\\"https://images.unsplash.com/photo-1725203574073-79922f64110a\\"\"" on `next/image`, if using relative image it must start with a leading slash "/" or be an absolute URL (http:// or https://)
```

**Comment by lanoow** [comment]
I got rid of the `\"` and stuff, however the image isn't rendered still.
![image](https://github.com/user-attachments/assets/4f629342-a4dc-4487-a56d-be20abab4584)

**Comment by lanoow** [comment]
@Aslam97 Still the same yeah. Here's the request tab.
![image](https://github.com/user-attachments/assets/b83140a4-2543-4bdb-89c0-48eb39bdb444)

I think this is the problem, for some reason there's `http://localhost:3000/` infront of the image but I have no idea where it comes from.

**Comment by lanoow** [comment]
@Aslam97 no, no I don't

**Comment by Aslam97** [comment]
@lanoow tried with nextjs and works fine for me

<img width="1537" alt="Screenshot 2024-10-02 at 16 55 53" src="https://github.com/user-attachments/assets/adb9ba35-539a-4d33-be0a-d8ec72077d69">

**Comment by lanoow** [comment]
@Aslam97 I guess it could be because of the `next-intl` package or `authjs`.

**Comment by lanoow** [comment]
Here's my middleware.ts file
```ts
import createMiddleware from 'next-intl/middleware';
import { NextRequest } from 'next/server';
import authConfig from "../auth.config";
import {routing} from './i18n/routing';
import NextAuth from "next-auth";

const handleI18nRouting = createMiddleware(routing);

const { auth } = NextAuth(authConfig);

export default auth(async function middleware(req: NextRequest) {
	return handleI18nRouting(req);
});

export const config = {
	matcher: [
		"/((?!api|static|.*\\..*|_next|favicon.ico|logo.png|robots.txt).*)",
		"/(en|bg)/:path*",
		"/dashboard/:path*"
	]
}
```

**Comment by Aslam97** [comment]
@lanoow try this

```
export const config = {
  matcher: [
    // Skip Next.js internals and static files
    "/((?!_next|static).*)",
    
    // Include specific file types in search params
    "/(.*\\?.*(\\.html?|\\.css|\\.js|\\.json|\\.jpe?g|\\.webp|\\.png|\\.gif|\\.svg|\\.ttf|\\.woff2?|\\.ico|\\.csv|\\.docx?|\\.xlsx?|\\.zip|\\.webmanifest))",
    
    // Always run for API and tRPC routes
    "/(api|trpc)/.*",
    
    // mine
    "/(en|bg)/:path*",
    "/dashboard/:path*"
  ]
};
```

**Comment by Aslam97** [comment]
@lanoow you could try asking on Claude(dot)ai about regex.

**Comment by lanoow** [comment]
> @lanoow try this
> 
> ```ts
> export const config = {
>   matcher: [
>     // Skip Next.js internals and all static files, unless found in search params
>     "/((?!_next|[^?]*\\.(?:html?|css|js(?!on)|jpe?g|webp|png|gif|svg|ttf|woff2?|ico|csv|docx?|xlsx?|zip|webmanifest)).*)",
>     // Always run for API and tRPC routes
>     "/(api|trpc)/.*",
>     
>     // mine
>     "/(en|bg)/:path*",
>     "/dashboard/:path*"
>   ]
> };
> ```

Tried it, still the same, no change.

**Comment by Aslam97** [comment]
@lanoow hei do you solve this? if yes I ll close this issue

**Comment by lanoow** [comment]
@Aslam97 um, no I haven't figured it out. I'll close it if i find a solution.

**Comment by lanoow** [comment]
No solution found. Issue seems to be with the project.
