### ISSUE TITLE
Request: Code Block Syntax Highligh

### ISSUE THREAD

**Issue by markkop-halborn** [Aslam97/shadcn-minimal-tiptap#28]
Hey!
I'm trying, but I can't make it compatible with tiptap code syntax highlight. Any suggestions on how implement this?
https://tiptap.dev/docs/examples/advanced/syntax-highlighting

**Comment by Aslam97** [comment]
@markkop-halborn you can customize the extension here https://github.com/Aslam97/shadcn-minimal-tiptap/blob/main/src/components/minimal-tiptap/extensions/code-block-lowlight/code-block-lowlight.ts

**Comment by markkop-halborn** [comment]
Will give it a try, thanks!

**Comment by Aslam97** [comment]
@markkop-halborn do you solve it?
