### ISSUE TITLE
How to use Image extension?

### ISSUE THREAD

**Issue by aldiabdumalik** [Aslam97/shadcn-minimal-tiptap#44]
How to use an image extension within a page file? 
![image](https://github.com/user-attachments/assets/5e4b03e4-8996-45aa-bab7-cac46162adf6)

**Comment by Aslam97** [comment]
@aldiabdumalik if you follow the install instructions, you can directly edit the file at https://github.com/Aslam97/shadcn-minimal-tiptap/blob/main/src/components/minimal-tiptap/hooks/use-minimal-tiptap.ts and implement your own upload function

**Comment by aldiabdumalik** [comment]
ok, thank u👍

**Comment by Aslam97** [comment]
@aldiabdumalik atau tanya langsung di sini https://www.facebook.com/groups/442974152553174/?multi_permalinks=2797986420385257&notif_id=1729204504867943&notif_t=feedback_reaction_generic&ref=notif
