### ISSUE TITLE
Upload image only on trigger

### ISSUE THREAD

**Issue by Th1nhNg0** [Aslam97/shadcn-minimal-tiptap#45]
Hey, I want to add image to the editor but only upload to my server when I click save, how can i do that?

**Comment by Aslam97** [comment]
@Th1nhNg0 I just added new feature called `onImageRemoved` and you can specify an id to it, so I gues you dont have to worry about images that are not used on the server

take a look
https://github.com/Aslam97/shadcn-minimal-tiptap/pull/46

**Comment by Th1nhNg0** [comment]
@Aslam97 wow, this is what I'm looking for, thank you

**Comment by Aslam97** [comment]
@Th1nhNg0 If thats solve your problem, I will close this issue for now. feel free reopen the issue.
