### ISSUE TITLE
Placeholder is moving with cursor

### ISSUE THREAD

**Issue by sahilverma-dev** [Aslam97/shadcn-minimal-tiptap#48]
https://github.com/user-attachments/assets/183f9bac-1167-47ca-a8ee-241ead1f65c8

**Comment by Aslam97** [comment]
@sahilverma-dev That is the default behavior when there is no content in the editor.

**Comment by sahilverma-dev** [comment]
> @sahilverma-dev That is the default behavior when there is no content in the editor.

How can I turn this off if I don’t want it?

**Comment by sahilverma-dev** [comment]
@Aslam97 Thank you so much for your help and such incredible repository. It truly means a lot!

**Comment by Aslam97** [comment]
@sahilverma-dev I'm glad it help!. I'll close this issue since it seems you've resolved it. Feel free to create a new issue or reopen this one.
