### ISSUE TITLE
Image upload feature absolutely free? and will work on production?

### ISSUE THREAD

**Issue by markbulingit** [Aslam97/shadcn-minimal-tiptap#55]
I was surprised to know that the image upload on this project is fully working! I thought this is only possible on PRO version.
Can you confirm this?

**Comment by Aslam97** [comment]
@markbulingit Yeah it's totally working! And nope, no PRO version or anything, it's all free!.

**Comment by Aslam97** [comment]
@markbulingit Based on my previous response, I believe you get the answer. I am gonna close this issue for now. feel free to reopen or create a new one.
