### ISSUE TITLE
uploadFn executes twice

### ISSUE THREAD

**Issue by markbulingit** [Aslam97/shadcn-minimal-tiptap#56]
I use Supabase to store the images, problem is it gets executed twice.

On this image, I just upload one image but got 2 identical images.
![image](https://github.com/user-attachments/assets/80651868-e71c-4f59-b870-8bca99a146c9)

**Comment by markbulingit** [comment]
@Aslam97 awesome man! thank you for quick response the problem has been fixed, just one more bug I noticed here's to reproduce:

Situation #1: 
1. Do not type anything on the editor.
2. Just straight up upload an image file.
3. Check the onChange value of editor.
4. NO VALUE, even if there's an image successfully uploaded.

![image](https://github.com/user-attachments/assets/7cb03cc7-8fb0-4523-bde7-9bc2526e68d8)


Situation #2:
1. Type something on the editor.
2. Upload an image file.
3. Check the onChange value of editor.
4. VALUE IS PRESENT -everything is good.

![image](https://github.com/user-attachments/assets/e6dd373b-232d-494b-8ae9-522338e2c7c3)

**Comment by Aslam97** [comment]
@markbulingit Could you create a new issue for it? It's not related to the current issue. I'll close this issue now since the original problem has been fixed.

**Comment by ngocnguyenquang-agilityio** [comment]
> [@Aslam97](https://github.com/Aslam97) awesome man! thank you for quick response the problem has been fixed, just one more bug I noticed here's to reproduce:
> 
> Situation [#1](https://github.com/Aslam97/shadcn-minimal-tiptap/issues/1):
> 
> 1. Do not type anything on the editor.
> 2. Just straight up upload an image file.
> 3. Check the onChange value of editor.
> 4. NO VALUE, even if there's an image successfully uploaded.
> 
> ![image](https://github.com/user-attachments/assets/7cb03cc7-8fb0-4523-bde7-9bc2526e68d8)
> 
> Situation [#2](https://github.com/Aslam97/shadcn-minimal-tiptap/issues/2):
> 
> 1. Type something on the editor.
> 2. Upload an image file.
> 3. Check the onChange value of editor.
> 4. VALUE IS PRESENT -everything is good.
> 
> ![image](https://github.com/user-attachments/assets/e6dd373b-232d-494b-8ae9-522338e2c7c3)

Hi @Aslam97, is the above issue solved? If not, could you provide the link to this issue (just for tracking easier).
