### ISSUE TITLE
SAVE button in the toolbar

### ISSUE THREAD

**Issue by softshipper** [Aslam97/shadcn-minimal-tiptap#59]
Hi @Aslam97,

One question, how can I add a custom button to the toolbar? I would like to add the save button.

Best regards

**Comment by Aslam97** [comment]
@softshipper I not sure why you want to add save button in the toolbar. but here example:

1. in the `minimal-tiptap.tsx` there is a component called `Toolbar` https://github.com/Aslam97/shadcn-minimal-tiptap/blob/main/src/components/minimal-tiptap/minimal-tiptap.tsx#L25 
2. You can see the last section of the toolbar is `<SectionFive editor={editor} activeActions={['codeBlock', 'blockquote', 'horizontalRule']} mainActionCount={0} />`
3. Now you can paste below code after the `<SectionFive />`

```ts
      <ToolbarButton
        onClick={() => save()}       
        tooltip={'Save'}
        aria-label={'Save'}
        size={'sm'}
        variant={'secondary'}
      >
        Save
      </ToolbarButton>
```
