### ISSUE TITLE
Buggy Strikethrough Behaviour

### ISSUE THREAD

**Issue by softmarshmallow** [Aslam97/shadcn-minimal-tiptap#61]
https://github.com/user-attachments/assets/2682a35e-84d1-41bb-a93d-8b62e9b57a5b

The strikethrough will first be applied, menu closes, then gone, after focusing in the input area, it then renders.

MRE: https://shadcn-minimal-tiptap.vercel.app/

**Comment by Aslam97** [comment]
@softmarshmallow Thanks for reporting this!. fixed 0c83971
