### ISSUE TITLE
Saving JSON to database

### ISSUE THREAD

**Issue by lanoow** [Aslam97/shadcn-minimal-tiptap#63]
Hi,

I'm using Prisma with Mongo to save my content, I'm saving it as JSON and after it's saved the content get's rendered as this:
![image](https://github.com/user-attachments/assets/f37e41eb-47f8-4d52-9313-7e54a4cfdde0)

Any ideas?

**Comment by Aslam97** [comment]
@lanoow Try convert the json string into json

**Comment by lanoow** [comment]
@Aslam97 I'm converting it to `Content` since the `value` prop doesn't accept anything else

**Comment by lanoow** [comment]
Saving it as `html` works except for the images, I get `invalid url, url cannot be created` error.
![image](https://github.com/user-attachments/assets/73959a06-54f3-4966-9897-ecc38691cb22)
![image](https://github.com/user-attachments/assets/a0951352-3aca-438d-935e-9ffe6b5f23fd)

**Comment by lanoow** [comment]
I tried saving it in the database as a `JsonObject`, however, no luck at rendering it for some reason. Saving it as `HTML`, parses it in a weird way.
```
"<p class=\"text-node\"><strong>miamefiemfmek</strong></p><p class=\"text-node\"></p><img src=\"https://utfs.io/f/UPgcVMIhDRfdzGexgpkN7q6ZCnQ0ERfBKU41oev2id9SuXpY\" alt=\"\" title=\"\" id=\"UPgcVMIhDRfdzGexgpkN7q6ZCnQ0ERfBKU41oev2id9SuXpY\" width=\"600\" height=\"465\" filename=\"266358_l.jpeg\">"
```
![image](https://github.com/user-attachments/assets/f573824c-924e-4bc0-8b9f-d6f1cd643ad4)

**Comment by lanoow** [comment]
Also whenever there's an empty input and save it multiple times, it creates this weird thing and fills it up with `"` and `\`

**Comment by lanoow** [comment]
Okay, apparently I've added JSON.stringify to the server action that saves the content to the database and have forgotten about it. Everything works now, one last question though, I'm using UpoadThing for the image uploads, what would you recommend? Saving them as base64 or uploading them to uploadthing?

**Comment by Aslam97** [comment]
@lanoow Glad you solved it!. For handling images, I recommend uploading to the server if the file size is larger than 2MB

**Comment by lanoow** [comment]
@Aslam97 thank you.
