### ISSUE TITLE
The selected state of the photo

### ISSUE THREAD

**Issue by TinsFox** [Aslam97/shadcn-minimal-tiptap#66]
I have a question🤔, when the editor disables editing, should the photo still be able to be selected and add an outline style?
<img width="1911" alt="image" src="https://github.com/user-attachments/assets/265c256b-8e4a-44ac-9f9a-a2fb34b83258">

**Comment by Aslam97** [comment]
@TinsFox If editing is disabled, photos should still be selectable but without the ability to resize etc. but you can always configure to your need.

**Comment by TinsFox** [comment]
Thank you for your explanation, thank you!
