### ISSUE TITLE
Adding the resize feature

### ISSUE THREAD

**Issue by Snouzy** [Aslam97/shadcn-minimal-tiptap#8]
Hello,
is it planned to add the resize feature for an image ?

**Comment by Aslam97** [comment]
@Snouzy I was thinking about implement this feature. where users can position and resize the image. However, at the moment, it's not a priority for me as there's no urgent need for this feature in my internal use case. PR are welcome.

**Comment by Snouzy** [comment]
Understood. Not so many time on my side for the moment but i'll keep this in mind. Thanks !

**Comment by Aslam97** [comment]
Hi @Snouzy, the image resize feature is currently in development, but you should be able to test it locally. The only missing feature is the ability to upload the image to the server, which will be done before this weekend. You can check PR #27 for details. If you have any feedback, please let me know what you think.

**Comment by Snouzy** [comment]
Good job ! 🎊
